# Generated by Django 5.1.3 on 2025-01-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_precoservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precoservico',
            name='usuarios',
            field=models.IntegerField(max_length=10, verbose_name='Usuários'),
        ),
    ]
